### ISSUE TITLE
Document all our everything

### ISSUE THREAD

**Issue by mplewis** [teslaworksumn/teslaworks.net#160] opened 2013-10-29 20:19 UTC
## also known as
# Technical Debt: The Debtening

![dse](https://f.cloud.github.com/assets/1829094/1431983/5ee6b4d6-40d7-11e3-9092-42af2dcc2c12.jpg)

Python Docstring everything.

Comment our build files.

Put stuff in the wiki.

**Comment by taylortrimble** [comment] 2013-10-30 19:49
Dupe of #39.

**Closed as completed by taylortrimble** 2013-10-30 19:49 UTC
Labels: duplicate
